// Database types for Vector PWA
// This file will be auto-generated by Supabase CLI in production
// For now, we define types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Role = 'owner' | 'manager' | 'personnel';
export type ResourceType = 'notes' | 'tasks' | 'personnel';
export type TaskStatus = 'open' | 'closed';

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          invite_code: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          invite_code: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          invite_code?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string;
          role: Role;
          name: string;
          surname: string;
          username: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id: string;
          role: Role;
          name: string;
          surname: string;
          username: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          role?: Role;
          name?: string;
          surname?: string;
          username?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      permissions: {
        Row: {
          id: string;
          organization_id: string;
          role: Role;
          resource_type: ResourceType;
          can_view: boolean;
          can_create: boolean;
          can_edit: boolean;
          can_delete: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          role: Role;
          resource_type: ResourceType;
          can_view?: boolean;
          can_create?: boolean;
          can_edit?: boolean;
          can_delete?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          role?: Role;
          resource_type?: ResourceType;
          can_view?: boolean;
          can_create?: boolean;
          can_edit?: boolean;
          can_delete?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      personnel: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      notes: {
        Row: {
          id: string;
          personnel_id: string;
          author_id: string;
          content: string;
          is_voice_note: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          personnel_id: string;
          author_id: string;
          content: string;
          is_voice_note?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          personnel_id?: string;
          author_id?: string;
          content?: string;
          is_voice_note?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          personnel_id: string;
          description: string;
          deadline: string;
          status: TaskStatus;
          star_rating: number | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          personnel_id: string;
          description: string;
          deadline: string;
          status?: TaskStatus;
          star_rating?: number | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          personnel_id?: string;
          description?: string;
          deadline?: string;
          status?: TaskStatus;
          star_rating?: number | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_analyses: {
        Row: {
          id: string;
          personnel_id: string;
          strengths: Json;
          development_areas: Json;
          raw_response: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          personnel_id: string;
          strengths: Json;
          development_areas: Json;
          raw_response?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          personnel_id?: string;
          strengths?: Json;
          development_areas?: Json;
          raw_response?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_organization_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_user_role: {
        Args: Record<PropertyKey, never>;
        Returns: Role;
      };
      has_permission: {
        Args: {
          p_resource_type: ResourceType;
          p_action: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
